FROM tensorflow/tensorflow:2.9.1-gpu

RUN apt-get update && apt-get install -y libopenexr-dev
RUN pip install pydicom==2.2.2 h5py==3.11.0 \
scikit-learn==1.3.2 scikit-image==0.21.0 matplotlib==3.7.5 \
tensorflow-addons==0.21.0 nibabel==5.2.1 \
"typing_extensions==4.13.2"

RUN apt-get update && apt-get install -y libopenexr-dev

RUN pip install --no-cache-dir \
    pydicom==2.2.2 \
    pylibjpeg==1.4.0 \
    pylibjpeg-libjpeg==1.3.4 \
    pylibjpeg-openjpeg==1.3.2 \
    streamlit==1.40.1 \
    stqdm==0.0.5 \
    opencv-python-headless==4.13.0.92 \
    streamlit_drawable_canvas==0.9.3 \
    monai==1.3.2

RUN pip install --no-cache-dir \
    torch==2.3.0 \
    torchvision==0.18.0 \
    torchaudio==2.3.0 \
    --index-url https://download.pytorch.org/whl/cu121

RUN apt-get update \
    && apt-get install -y --no-install-recommends git ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/mrphys/im2sim.git /tmp/im2sim \
    && cd /tmp/im2sim \
    && git checkout 18ad52d \
    && pip install -r requirements.txt \
    && pip install . \
    && rm -rf /tmp/im2sim

RUN pip uninstall protobuf -y
RUN pip install protobuf==3.20.3